# Generated by Django 4.1.5 on 2023-01-21 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baits',
            options={'ordering': ['name'], 'verbose_name': 'Bait', 'verbose_name_plural': 'Baits'},
        ),
        migrations.AlterModelOptions(
            name='fish',
            options={'ordering': ['name'], 'verbose_name': 'Fish', 'verbose_name_plural': 'Fish'},
        ),
        migrations.AlterModelOptions(
            name='spots',
            options={'ordering': ['title'], 'verbose_name': 'Spot', 'verbose_name_plural': 'Spots'},
        ),
    ]
