# Generated by Django 4.1.5 on 2023-01-22 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_alter_baits_options_alter_fish_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spots',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='fish',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
