# Generated by Django 4.1.5 on 2023-01-24 11:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0003_spots_rating_alter_fish_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='baits',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/baits/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
