# Generated by Django 4.1.5 on 2023-01-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0005_baits_time_create_baits_time_update_fish_time_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baits',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Bait'),
        ),
        migrations.AlterField(
            model_name='baits',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fish',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='spots',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='spots',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
