# Generated by Django 4.1.5 on 2023-01-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0006_alter_baits_name_alter_baits_slug_alter_fish_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spots',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
