# Generated by Django 4.1.5 on 2023-01-24 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0007_alter_spots_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baits',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='fish',
            name='average_weight',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(70.0), django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='spots',
            name='max_depth',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
