# Generated by Django 4.1.5 on 2023-01-27 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0008_alter_baits_price_alter_fish_average_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Fish category')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Fish category',
                'verbose_name_plural': 'Fish categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpotCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Spot category')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Spot category',
                'verbose_name_plural': 'Spot categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='baits',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Bait name'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='average_weight',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(70.0), django.core.validators.MinValueValidator(0.1)], verbose_name='Average weight'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Fish name'),
        ),
        migrations.AlterField(
            model_name='spots',
            name='max_depth',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Max depth'),
        ),
        migrations.AlterField(
            model_name='spots',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Spot name'),
        ),
    ]
