# Generated by Django 4.1.5 on 2023-01-27 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0009_fishcategory_spotcategory_alter_baits_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='fish_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='spots.fishcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spots',
            name='spot_category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='spots.spotcategory'),
            preserve_default=False,
        ),
    ]
