# Generated by Django 4.1.5 on 2023-01-27 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0010_fish_fish_category_spots_spot_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='average_weight',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(200.0), django.core.validators.MinValueValidator(0.1)], verbose_name='Average weight'),
        ),
        migrations.AlterField(
            model_name='spots',
            name='max_depth',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(1)], verbose_name='Max depth'),
        ),
    ]
