# Generated by Django 4.1.5 on 2023-02-25 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0013_spots_dislikes_spots_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spots',
            name='dislikes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='spots',
            name='likes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
